/*
    BLAUGRANA MANAGEMENT SYSTEM
    Script 03 - Llaves foraneas y relaciones entre tablas
    Motor: Microsoft SQL Server
*/

USE BlaugranaDB;
GO

ALTER TABLE USUARIO
    ADD CONSTRAINT FK_USUARIO_ROL
    FOREIGN KEY (id_rol) REFERENCES ROL(id_rol);
GO

ALTER TABLE CONTRATO
    ADD CONSTRAINT FK_CONTRATO_JUGADOR
    FOREIGN KEY (id_jugador) REFERENCES JUGADOR(id_jugador);
GO

ALTER TABLE PARTICIPACION_PARTIDO
    ADD CONSTRAINT FK_PARTICIPACION_PARTIDO
    FOREIGN KEY (id_partido) REFERENCES PARTIDO(id_partido);
GO

ALTER TABLE PARTICIPACION_PARTIDO
    ADD CONSTRAINT FK_PARTICIPACION_JUGADOR
    FOREIGN KEY (id_jugador) REFERENCES JUGADOR(id_jugador);
GO

ALTER TABLE BONIFICACION
    ADD CONSTRAINT FK_BONIFICACION_JUGADOR
    FOREIGN KEY (id_jugador) REFERENCES JUGADOR(id_jugador);
GO

ALTER TABLE BONIFICACION
    ADD CONSTRAINT FK_BONIFICACION_PARTIDO
    FOREIGN KEY (id_partido) REFERENCES PARTIDO(id_partido);
GO

ALTER TABLE PAGO
    ADD CONSTRAINT FK_PAGO_JUGADOR
    FOREIGN KEY (id_jugador) REFERENCES JUGADOR(id_jugador);
GO

ALTER TABLE PAGO
    ADD CONSTRAINT FK_PAGO_CONTRATO
    FOREIGN KEY (id_contrato) REFERENCES CONTRATO(id_contrato);
GO

ALTER TABLE INGRESO
    ADD CONSTRAINT FK_INGRESO_CATEGORIA
    FOREIGN KEY (id_categoria_ingreso) REFERENCES CATEGORIA_INGRESO(id_categoria_ingreso);
GO

ALTER TABLE EGRESO
    ADD CONSTRAINT FK_EGRESO_CATEGORIA
    FOREIGN KEY (id_categoria_egreso) REFERENCES CATEGORIA_EGRESO(id_categoria_egreso);
GO

ALTER TABLE DETALLE_PRESUPUESTO
    ADD CONSTRAINT FK_DETALLE_PRESUPUESTO
    FOREIGN KEY (id_presupuesto) REFERENCES PRESUPUESTO(id_presupuesto);
GO
